<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net35</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<NoWarn>CS0649;NUnit2005;CS8602;CS8618</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.4" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
		<PackageReference Include="NUnit" Version="2.6.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\mscorlib.NET35\Net35.MsCorlib.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="NUnit.Framework" />
	</ItemGroup>

</Project>